CREATE DATABASE IF NOT EXISTS Grocery;
USE Grocery;

CREATE TABLE IF NOT EXISTS Store(
	ID VARCHAR(8) PRIMARY KEY, 
	geom_loc POINT NOT NULL,
	Name VARCHAR(100) NOT NULL, 
	SPATIAL INDEX (geom_loc)
);

CREATE TABLE IF NOT EXISTS Product(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	Name VARCHAR(20) NOT NULL UNIQUE
);


CREATE TABLE IF NOT EXISTS Item(
	ID INT AUTO_INCREMENT, 
	Store_ID VARCHAR(8), 
	Product_ID INT, 
	Name VARCHAR(200) NOT NULL,
	Price Decimal(5, 2) UNSIGNED NOT NULL,
	TS DATE DEFAULT (CURRENT_DATE),
	PRIMARY KEY (ID, Store_ID, Product_ID),
	FOREIGN KEY (Store_ID) REFERENCES Store(ID),
	FOREIGN KEY (Product_ID) REFERENCES Product(ID),
	UNIQUE (Store_ID, Product_ID, Name)
);


CREATE TABLE IF NOT EXISTS User(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	Email VARCHAR(30) NOT NULL UNIQUE,
	Password VARCHAR(255) NOT NULL
);


CREATE TABLE IF NOT EXISTS Orders(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	User_ID INT NOT NULL,
	Name VARCHAR(20) NOT NULL,
	Total DECIMAL(10,2) NOT NULL, 
	FOREIGN KEY (User_ID) REFERENCES User(ID)
);

CREATE TABLE IF NOT EXISTS User_Order(
	Item_ID INT,
	Store_ID VARCHAR(8), 
	Product_ID INT,
	Order_ID INT,
	Quantity INT NOT NULL,
	Individual_Total DECIMAL(6,2) NOT NULL,
	PRIMARY KEY (Item_ID, Store_ID, Product_ID, Order_ID),
	FOREIGN KEY (Item_ID, Store_ID, Product_ID) REFERENCES Item(ID, Store_ID, Product_ID),
	FOREIGN KEY (Order_ID) REFERENCES Orders(ID)
);
